### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [jenssegers/zsh#3]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

Also, please consider renaming this repo to something less generic - maybe jenssegers.zsh-theme?

**Comment by jenssegers** [comment]
Added MIT 👌

**Comment by unixorn** [comment]
That was quick :-)

**Comment by jenssegers** [comment]
Will check out what other people call their repositories and update the Readme a bit tomorrow 👌

**Comment by unixorn** [comment]
Cool. Either update this issue when you change the name or just make a PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), whatever's easier for you.

**Comment by jenssegers** [comment]
Renamed the repository to jenssegers/palenight.zsh-theme. Thanks for the feedback!

**Comment by unixorn** [comment]
Added, thanks!
